### PR TITLE
MMB insurance: fetch passengers from the API

### PR DESCRIPTION
**Pull request by mrtnzlml**

### CODE REVIEW

**Comment by mrtnzlml** [comment]
Must be rebased after https://github.com/kiwicom/mobile/pull/758 - I messed this up.

**Comment by tbergq** [comment]
Some test is unhappy

**Comment by mrtnzlml** [comment]
@tbergq 

> Must be rebased after #758 - I messed this up.

:)

**Comment by mrtnzlml** [comment]
@tbergq 🚀

**Pull request merged**
