### PR TITLE
Fix: Single Hotel Details - see picture detail instead of gallery

### PR DESCRIPTION
**Pull request by RobinCsl**

### CODE REVIEW

**Comment by tbergq** [comment]
Who asked for this change? I really don't like it. 

First of all, if I have the thumbnails, I can find and enlarge the fotos that interests me. Probably I would want to see 2 or 3 out of 120 photos. 

Second, it does not make sense to directly open a modal with images, then when I close it, I am at the grid. I would expect to end up where I was when I clicked the photo.

**Comment by RobinCsl** [comment]
So after our discussion from this morning, what do you think we should be doing about this one?

**Comment by tbergq** [comment]
🤷‍♂️ One one replied to it yet. I would say two options

1. Leave it as is (my preferred way)
2. Open the modal (🙈) then when you close it, you are on hotel detail screen, and just delete gallery screen.

**Comment by RobinCsl** [comment]
Okay, let's wait for a reply from someone.

**Comment by RobinCsl** [comment]
After discussion with designer: 
> ​​Well okay, let’s keep gallery view
So closing this issue.

**Pull request closed without merging**
