### PR TITLE
Use color constants directly - remove usage of native RNColors bridge

### PR DESCRIPTION
**Pull request by mrtnzlml**

### CODE REVIEW

**Comment by tbergq** [comment]
@mrtnzlml check your tests

**Comment by mrtnzlml** [comment]
@tbergq There is nothing to fix.

**Comment by tbergq** [comment]
skjermbilde 2018-05-22 kl 10 51 41

**Comment by mrtnzlml** [comment]
Open it first, please.

**Comment by tbergq** [comment]
Yes, I see it is timeout, works locally, so I will merge

**Comment by mrtnzlml** [comment]
See: https://status.npmjs.org/ - Increased registry response time

We don't need to wait for them.

**Pull request merged**
