### PR TITLE
Rename fast track translation keys

### PR DESCRIPTION
**Pull request by vblazenka**

### CODE REVIEW

**Comment by RobinCsl** [comment]
@vblazenka I had to force push your branch and amend your commits since you had committed some tokens... Please, be careful. Hopefully, I did not lose any of your work in the process.

**Comment by vblazenka** [comment]
@tbergq are you sure? It didn't add any prefix... that's why I added it manually

**Comment by tbergq** [comment]
> @tbergq are you sure? It didn't add any prefix... that's why I added it manually

Take any string from `Hotels.js`, log into phraseApp, and you will see it has been added there with `.mobile` as prefix. 

Also, check how we use it in the application. Our code adds the prefix where it is needed. Since we are not 🐒 we don't want to write this prefix that mobile team for some reason insists on repeating everywhere. We are smarter than that 😊

**Comment by vblazenka** [comment]
> > @tbergq are you sure? It didn't add any prefix... that's why I added it manually
> 
> Take any string from `Hotels.js`, log into phraseApp, and you will see it has been added there with `.mobile` as prefix.
> 
> Also, check how we use it in the application. Our code adds the prefix where it is needed. Since we are not 🐒 we don't want to write this prefix that mobile team for some reason insists on repeating everywhere. We are smarter than that 😊

I see that yeah. But when I ran `deploy-translations` the script didn't add any `mobile.` prefix. So I had to do the `mobile.` part manually.

**Comment by tbergq** [comment]
Where did you expect the prefix to be added?

**Comment by vblazenka** [comment]
> Where did you expect the prefix to be added?

Well if I named my key `mmb.fast_track.banner.description.bergamo.bergamo_stopover` I expected to see `mobile.mmb.fast_track.banner.description.bergamo.bergamo_stopover` on the PhraseApp if I understood exactly.

**Comment by tbergq** [comment]
Well, if you want to call your keys `mobile.mmb.your_key` I woun't stop you, but know that it will be uploaded to phraseApp as `mobile.mobile.mmb.your_key`

**Pull request closed without merging**
