### PR TITLE
Feature: Improving logging module for Hotels

### PR DESCRIPTION
**Pull request by RobinCsl**
This is pending on #1299 
It will also be necessary to bump the RN native modules and RNKiwiMobile versions, and probably do something with CodePush too.

### CODE REVIEW

**Comment by RobinCsl** [comment]
@ferrannp @Blackhex Could you please have a look at this PR? Thank you!

**Comment by Blackhex** [comment]
I haven't check if it complies with the actual logs definition but from the technical point of view it seems OK.

**Comment by tbergq** [comment]
Is this ready to be merged
@RobinCsl @ferrannp @Blackhex

**Comment by RobinCsl** [comment]
I think I wanted one last review by @ferrannp but forgot to ask for it 😊, and then we should be able to merge it.

**Pull request merged**
