### PR TITLE
Hotels: Extend logging

### PR DESCRIPTION
**Pull request by tbergq**
Still missing `hotelsBookNowPressed` because ios needs to change NSNumber to nonnull NSNumber. 

Still missing `hotelsDetailAbandoned` I would like some clarification on how to log it.

### CODE REVIEW

**Comment by RobinCsl** [comment]
@pistelak Could you please have a look at the issue with this not nonnull `NSNumber`? Thank you
simulator screen shot - iphone x - 2018-12-17 at 18 02 04

**Comment by pistelak** [comment]
Will do :)

**Comment by tbergq** [comment]
Any reason this PR has not been merged @RobinCsl ? I was thinking to add the missing logs in other PR?

**Comment by pistelak** [comment]
@RobinCsl is probably waiting for the fix I'm working on. I've just fixed it. Please, give me a few minutes... :)

**Comment by tbergq** [comment]
But your fix is unrelated to this PR @pistelak

**Comment by pistelak** [comment]
Ok, 😶

**Pull request merged**
